services:

    ollama:
        image: ollama/ollama:latest
        ports:
            - 11434:11434
        volumes:
            - ./.ollama:/root/.ollama

    # bot:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile


    #docker compose up -d
    #docker compose exec ollama ollama pull tinyllama:1.1b-chat-v0.6-q2_K
